import Head from 'next/head'
import Image from 'next/image'
import HeroSection from '../components/hero-section'
import ListSection from '../components/list-section'
import FeaturesSection from '../components/features-section'
import CasesSection from '../components/cases-section'
import SocialProof from '../components/social-proof'
import PricingTable from '../components/pricing-table'
import Footer from '../components/footer'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <HeroSection />
                <ListSection />
                <FeaturesSection />
                <CasesSection />
                <SocialProof />
                <PricingTable />
            </main>
            <Footer />
        </>
    )
}
